spring:
  application:
    name: moa
  profiles:
    active: trace

  # Database
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      format_sql: true
    show-sql: true

  # redis
  data:
    redis:
      port: 6379
      password: gosl111
      host: localhost

# web security config
jwt:
  secret-key: aGFlbmktand0LWxvZ2luLXByai1qd3Qtc2VjcmV0LWtleQo=
  encrypt-key: aGFlbmktand0LWxvZ2luLXByai1qd3QtZW5jcnlwdC1rZXkK
  access:
    token-header-name: Authorization
    expire-milliseconds: 1800000
    #expire-milliseconds: 10000
  refresh:
    expire-milliseconds: 3600000
    token-header-name: Authorization-Refresh

