spring:
  application:
    name: moa

  # Database
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
    properties:
      format_sql: true
    show-sql: true

# web security config
jwt:
  secret-key: aGFlbmktand0LWxvZ2luLXByai1qd3Qtc2VjcmV0LWtleQo=
  encrypt-key: aGFlbmktand0LWxv
  access:
    token-header-name: Authorization
    expire-milliseconds: 1800000
    #expire-milliseconds: 10000
  refresh:
    expire-milliseconds: 3600000
    token-header-name: Authorization-Refresh

# redis
  data:
    redis:
      password: gosl111
      port: 6379